# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-09-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190319_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='url',
            field=models.SlugField(help_text='Give the posting a short slug to be used in the url'),
        ),
    ]
