# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-19 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symposion_speakers', '0003_auto_20170419_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created'),
        ),
    ]
