# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2021-09-12 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_auto_20190630_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkproposal',
            name='what_attendees_will_learn',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tutorialproposal',
            name='what_attendees_will_learn',
            field=models.TextField(default=''),
        ),
    ]
